# Generated by Django 3.2.25 on 2026-03-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travel', '0002_auto_20260317_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractionrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attraction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attractionrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attractionrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='attractionrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attractionrating',
            unique_together={('user', 'attraction')},
        ),
    ]
