# Generated by Django 3.2.25 on 2026-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20260318_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
